# Generated by Django 6.0.3 on 2026-03-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_create_comment_table'),
    ]

    operations = [
        # 모델명 변경: ToDoList → ToDo
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='ToDo',
        ),
        # 필드명 변경: author → user
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='user',
        ),
        # 메타 옵션 변경 (verbose_name 등)
        migrations.AlterModelOptions(
            name='todo',
            options={
                'verbose_name': '할 일',
                'verbose_name_plural': '할 일 목록',
            },
        ),
    ]
