# Generated by Django 6.0.3 on 2026-03-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_todolist_to_todo'),  # 이전 마이그레이션 파일명에 맞게 수정
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS todo;'),
    ]