# Generated by Django 6.0.3 on 2026-03-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_drop_todo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
