# Generated by Django 6.0.3 on 2026-03-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_modified_at_todo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/todo_default.png', null=True, upload_to='todo/%Y/%m/%d/thumbnail'),
        ),
    ]
